name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        xcodebuild build \
          -project "NYCiti Nav.xcodeproj" \
          -scheme "NYCiti Nav" \
          -destination "platform=iOS Simulator,name=iPhone 17,OS=latest" \
          -quiet
